pim_api_product_list:
    path: /products
    defaults: { _controller: pim_api.controller.product:listAction, _format: json }
    methods: [GET]

pim_api_product_get:
    path: /products/{code}
    defaults: { _controller: pim_api.controller.product:getAction, _format: json }
    methods: [GET]
